name: UNITTEST_REPORT
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: 'choose an env to run'
        type: environment
        default: 'dev'

      python_version:
        required: true
        description: 'choose preferred python version'
        default: '3.12'
        type: choice
        options:
          - 3.14
          - 3.12
          - 3.9
          - 3.8


env:
  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  PYTHON_VERSION: ${{ inputs.python_version == '' && 3.9 || inputs.python_version }}


jobs:
  PRINT_ISSUES_AND_LAST_COMMIT:
    runs-on: ubuntu-20.04
    environment: ${{ inputs.environment == '' && 'dev' || inputs.environment }}
    steps:
      - name: Tell me a secret!
        run: |
          echo "python version is: ${{ env.PYTHON_VERSION }} "


      - name: Setup python-version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cloning our repo
        uses: actions/checkout@v4

      - name: Pull or Push Cache to cloud
        uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run the python script
        run: python src/github_api.py

  UNIT_TEST:
    runs-on: ubuntu-20.04
    environment:  ${{ inputs.environment == '' && 'dev' || inputs.environment }}
    steps:
      - name: Cloning our repo
        uses: actions/checkout@v4

      - name: Setup python-version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Pull or Push Cache to cloud
        uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run the UNIT TEST script
        run: python3 -m unittest tests/test_github_api.py

  LINTING:
    runs-on: ubuntu-20.04
    environment:  ${{ inputs.environment == '' && 'dev' || inputs.environment }}
    steps:
      - name: Cloning our repo
        uses: actions/checkout@v4

      - name: Setup python-version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Pull or Push Cache to cloud
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run flake8 for syntax check
        run: flake8 src/github_api.py

      - name: Run black for formatting
        run: black src/github_api.py
