name: UNITTEST_REPORT
on: push

jobs:
  A_BUILD_JOB:
    runs-on: ubuntu-24.04
    steps:
      - name: A.1) Cloning our repo
        uses: actions/checkout@v4
      - name: Setup python-version
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: A.2) Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: A.3) Run the python script
        run: python src/github_api.py