name: UNITTEST_REPORT
on: push

jobs:

  PRINT_ISSUES_AND_LAST_COMMIT:
    runs-on: ubuntu-24.04
    steps:
      - name: Cloning our repo
        uses: actions/checkout@v4
      - name: Setup python-version
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run the python script
        run: python src/github_api.py


  UNIT_TEST:
    runs-on: ubuntu-24.04
    steps:
      - name: Cloning our repo
        uses: actions/checkout@v4
      - name: Setup python-version
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run the UNIT TEST script
        run: python3 -m unittest tests/test_github_api.py

  LINTING:
    runs-on: ubuntu-24.04
    steps:
      - name: Cloning our repo
        uses: actions/checkout@v4
      - name: Setup python-version
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run flake8 for syntax check
        run: flake8 src/github_api.py

      - name: Run flake8 for syntax check
        run: black src/github_api.py
